backend:
  image: ghcr.io/nutelllo/therapy-backend
  tag: "v1"
  ollamaUrl: "https://cindy-fax-musical-votes.trycloudflare.com/api/generate"
frontend:
  image: ghcr.io/nutelllo/therapy-frontend
  tag: "v1"
